## Numeros Primos

In [210]:
import numpy as np
M = 12203
A =  110
X = 1
temp = 0
contador_zanjas_primos = np.ones(10)*-2
zanjas_primos = np.zeros((10,9))    

In [211]:
for j in range(10000):
    X = X * A % M
    Frac = str(X / M)
    for i in Frac[2:15]:
        aux = contador_zanjas_primos!=-2
        contador_zanjas_primos = contador_zanjas_primos+aux*1
              
        if(contador_zanjas_primos[int(i)]==-2): 
            contador_zanjas_primos[int(i)] += 1
        
        else:
            temp, contador_zanjas_primos[int(i)] = contador_zanjas_primos[int(i)], -1
            if(temp >=8):
                temp = 8
            zanjas_primos[int(i)][temp] += 1
                

/op/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:15: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [212]:
zanjas_primos

array([[ 1306.,  1178.,  1050.,   955.,   869.,   756.,   763.,   590.,
         5564.],
       [ 1280.,  1139.,   997.,   961.,   823.,   773.,   781.,   594.,
         5589.],
       [ 1289.,  1144.,  1055.,   932.,   946.,   776.,   710.,   535.,
         5544.],
       [ 1304.,  1127.,  1072.,   913.,   843.,   783.,   771.,   589.,
         5551.],
       [ 1293.,  1141.,  1045.,   965.,   879.,   745.,   733.,   673.,
         5561.],
       [ 1310.,  1162.,  1048.,   958.,   874.,   741.,   713.,   635.,
         5522.],
       [ 1324.,  1186.,  1079.,   920.,   845.,   796.,   769.,   592.,
         5586.],
       [ 1311.,  1161.,  1083.,   938.,   920.,   775.,   744.,   566.,
         5566.],
       [ 1311.,  1173.,  1005.,   967.,   870.,   777.,   779.,   596.,
         5560.],
       [ 1293.,  1121.,  1073.,   946.,   869.,   743.,   735.,   574.,
         5587.]])

In [213]:
FO_primos = sum(zanjas_primos)

In [214]:
FO_primos

array([ 13021.,  11532.,  10507.,   9455.,   8738.,   7665.,   7498.,
         5944.,  55630.])

In [220]:
sumator = sum(FO_primos)
sumator

129990.0

In [221]:
FE_primos = []
for i in range(9):
    if(i==8):
        FE_primos.append(sumator*(0.9)**(i))
    else:
        FE_primos.append(sumator*(0.1)*(0.9)**(i))

In [222]:
FE_primos

[12999.0,
 11699.1,
 10529.190000000001,
 9476.2710000000006,
 8528.6439000000009,
 7675.7795100000012,
 6908.201559000001,
 6217.3814031000011,
 55956.432627900016]

In [223]:
chi_primos = sum(((FE_primos - FO_primos) ** 2)/FE_primos)

In [219]:
chi_primos

447460.40848344454

## Rutina del Sistema

In [224]:
import random

temp = 0

contador_zanjas_rutina = np.ones(10)*-2
zanjas_rutina = np.zeros((10,9)) 

In [225]:
for j in range(10000):
    Frac = str(random.random())
    for i in Frac[2:15]:
        aux = contador_zanjas_rutina!=-2
        contador_zanjas_rutina = contador_zanjas_rutina+aux*1
              
        if(contador_zanjas_rutina[int(i)]==-2): 
            contador_zanjas_rutina[int(i)] += 1
        
        else:
            temp, contador_zanjas_rutina[int(i)] = contador_zanjas_rutina[int(i)], -1
            if(temp >=8):
                temp = 8
            zanjas_rutina[int(i)][temp] += 1               
             

/op/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:14: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [226]:
zanjas_rutina

array([[ 1287.,  1109.,  1007.,   967.,   882.,   805.,   726.,   671.,
         5527.],
       [ 1233.,  1151.,  1088.,   910.,   845.,   744.,   714.,   583.,
         5584.],
       [ 1339.,  1153.,  1052.,   982.,   865.,   724.,   700.,   587.,
         5603.],
       [ 1250.,  1183.,  1025.,  1003.,   877.,   743.,   651.,   590.,
         5599.],
       [ 1333.,  1157.,  1076.,   934.,   870.,   739.,   716.,   590.,
         5619.],
       [ 1327.,  1197.,  1003.,   964.,   829.,   818.,   734.,   626.,
         5598.],
       [ 1332.,  1242.,  1058.,   895.,   837.,   776.,   761.,   658.,
         5631.],
       [ 1261.,  1163.,   987.,   897.,   880.,   770.,   681.,   632.,
         5593.],
       [ 1338.,  1165.,  1138.,   952.,   858.,   746.,   718.,   622.,
         5618.],
       [ 1253.,  1065.,  1061.,   941.,   873.,   772.,   726.,   589.,
         5612.]])

In [227]:
FO_rutina = sum(zanjas_rutina)
FO_rutina

array([ 12953.,  11585.,  10495.,   9445.,   8616.,   7637.,   7127.,
         6148.,  55984.])

In [228]:
FE_rutina = []
for i in range(9):
    if(i==8):
        FE_rutina.append(sumator*(0.9)**(i))
    else:
        FE_rutina.append(sumator*(0.1)*(0.9)**(i))

print(FE_rutina)
    
chi_rutina = sum(((FE_rutina - FO_rutina) ** 2)/FE_rutina)

[12999.0, 11699.1, 10529.190000000001, 9476.2710000000006, 8528.6439000000009, 7675.7795100000012, 6908.201559000001, 6217.3814031000011, 55956.432627900016]


In [229]:
chi_rutina

10.298150569298066

In [230]:
print("CHI Primos: ", chi_primos, "CHI Rutina: ", chi_rutina)

CHI Primos:  71.9527311524 CHI Rutina:  10.2981505693
